---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-tempo-operator
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: '-100'
# ---
# apiVersion: operators.coreos.com/v1
# kind: OperatorGroup
# metadata:
#   name: openshift-tempo-operator
#   namespace: openshift-storage
# spec:
#   upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/odf-operator.openshift-storage: ""
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: stable-4.14
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: mcg-operator-stable-4.14-redhat-operators-openshift-marketplace
#   namespace: openshift-storage
# spec:
#   channel: stable-4.14
#   installPlanApproval: Automatic
#   name: mcg-operator
#   source: redhat-operators
#   sourceNamespace: openshift-marketplace
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: ocs-operator-stable-4.14-redhat-operators-openshift-marketplace
#   namespace: openshift-storage
# spec:
#   channel: stable-4.14
#   installPlanApproval: Automatic
#   name: ocs-operator
#   source: redhat-operators
#   sourceNamespace: openshift-marketplace
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: odf-csi-addons-operator-stable-4.14-redhat-operators-openshift-marketplace
#   namespace: openshift-storage
# spec:
#   channel: stable-4.14
#   config:
#     tolerations:
#     - effect: NoSchedule
#       key: node.ocs.openshift.io/storage
#       operator: Equal
#       value: "true"
#   installPlanApproval: Automatic
#   name: odf-csi-addons-operator
#   source: redhat-operators
#   sourceNamespace: openshift-marketplace