opentelemetry-collector:
  config:
    exporters:
      otlphttp/example:
        endpoint: tempo-tempostack-distributor.tracing-system.svc.cluster.local
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          exporters: [spanmetrics, otlphttp/example]