apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'https://github.com/arslankhanali/openshift-observability'
    targetRevision: HEAD
  sources: []
  project: default
