---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-gitops-operator
  annotations:
    argocd.argoproj.io/sync-wave: '-100'

---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '-100'