# kubectl apply -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  name: tracegen
  namespace: bookinfo
spec:
  template:
    spec:
      containers:
        - name: tracegen
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/tracegen:latest
          command:
            - "./tracegen"
          args:
            - -otlp-endpoint=tempo-tempostack-distributor.tracing-system.svc.cluster.local:4317
            - -otlp-insecure
            - -duration=60s
            - -workers=1
      restartPolicy: Never
  backoffLimit: 4
#EOF